import { Router, type IRouter } from "express";
import healthRouter from "./health";
import profileRouter from "./profile";
import projectsRouter from "./projects";
import filesRouter from "./files";
import templatesRouter from "./templates";
import collaboratorsRouter from "./collaborators";
import deploymentsRouter from "./deployments";
import exploreRouter from "./explore";
import dashboardRouter from "./dashboard";
import starsRouter from "./stars";
import notificationsRouter from "./notifications";
import aiRouter from "./ai";
import aiMultiRouter from "./ai-multi";
import aiGatewayRouter from "./ai-gateway";
import agentRouter from "./agent";
import commentsRouter from "./comments";
import adminRouter from "./admin";
import settingsRouter from "./settings";
import authRouter from "./auth";
import exportRouter from "./export";
import formatRouter from "./format";
import feedbackRouter from "./feedback";
import integrationsRouter from "./integrations";
import migrationsRouter from "./migrations";
import githubRouter from "./github";
import lintRouter from "./lint";
import gitRouter from "./git";
import analyticsRouter from "./analytics";
import databaseRouter from "./database";
import snippetsRouter from "./snippets";
import alwaysOnRouter from "./always-on";
import containersRouter from "./containers";
import wsStatsRouter from "./ws-stats";
import reviewsRouter from "./reviews";
import liveSessionsRouter from "./live-sessions";
import searchRouter from "./search";
import oauthAppsRouter from "./oauth-apps";
import webhooksRouter from "./webhooks";
import environmentRouter from "./environment";
import organizationsRouter from "./organizations";
import portsRouter from "./ports";
import badgesRouter from "./badges";
import fileWatcherRouter from "./file-watcher";
import transfersRouter from "./transfers";
import sslRouter from "./ssl";
import snapshotsRouter from "./snapshots";
import replRouter from "./repl";
import githubPrRouter from "./github-pr";
import containerNetworkRouter from "./container-network";
import coverageRouter from "./coverage";
import readmeRouter from "./readme";
import dbSyncRouter from "./db-sync";
import imageBuilderRouter from "./image-builder";
import perfTestRouter from "./perf-test";
import licenseCheckerRouter from "./license-checker";
import todosRouter from "./todos";
import trafficRouter from "./traffic";
import execHistoryRouter from "./exec-history";
import wikiRouter from "./wiki";
import timeTrackingRouter from "./time-tracking";
import importAnalyzerRouter from "./import-analyzer";
import multiRegionRouter from "./multi-region";
import costOptimizerRouter from "./cost-optimizer";
import deployAlertsRouter from "./deploy-alerts";
import imageScanRouter from "./image-scan";
import socialCardsRouter from "./social-cards";
import incidentsRouter from "./incidents";
import feedsRouter from "./feeds";
import autoPatchRouter from "./auto-patch";
import typeDocsRouter from "./type-docs";
import embedRouter from "./embed";
import projectMigrationRouter from "./project-migration";
import apiTesterRouter from "./api-tester";
import errorTrackingRouter from "./error-tracking";
import fsDiffRouter from "./fs-diff";
import starterKitsRouter from "./starter-kits";
import onboardingAnalyticsRouter from "./onboarding-analytics";
import backupVerifyRouter from "./backup-verify";
import prReviewRouter from "./pr-review";
import forecastingRouter from "./forecasting";
import warmPoolRouter from "./warm-pool";
import trafficShapingRouter from "./traffic-shaping";
import languageServerRouter from "./language-server";
import complianceRouter from "./compliance";
import multiTenantRouter from "./multi-tenant";
import rollingUpdateRouter from "./rolling-update";
import autoMigrateRouter from "./auto-migrate";
import containerAlertsRouter from "./container-alerts";
import deployChangelogRouter from "./deploy-changelog";
import templateCiRouter from "./template-ci";
import funnelAnalyticsRouter from "./funnel-analytics";
import aiCommitRouter from "./ai-commit";
import fileEncryptionRouter from "./file-encryption";
import deploySecretRotationRouter from "./deploy-secret-rotation";
import fileLockingRouter from "./file-locking";
import containerDnsRouter from "./container-dns";
import aiNamingRouter from "./ai-naming";
import previewBotRouter from "./preview-bot";
import starterGenRouter from "./starter-gen";
import cdnCacheRouter from "./cdn-cache";
import aiSqlRouter from "./ai-sql";
import wafRouter from "./waf";
import execAuditRouter from "./exec-audit";
import slaMonitorRouter from "./sla-monitor";
import costTagsRouter from "./cost-tags";
import analyticsExportRouter from "./analytics-export";
import imageOptimizerRouter from "./image-optimizer";
import templateAnalyticsRouter from "./template-analytics";
import autoHealingRouter from "./auto-healing";
import fileNotificationsRouter from "./file-notifications";
import execTimeoutRouter from "./exec-timeout";
import aiStyleRouter from "./ai-style";
import trafficMirrorRouter from "./traffic-mirror";
import sslMonitorRouter from "./ssl-monitor";
import duplicationDetectorRouter from "./duplication-detector";
import networkPolicyRouter from "./network-policy";
import aiApiDesignRouter from "./ai-api-design";
import envPromotionRouter from "./env-promotion";
import fsMonitorRouter from "./fs-monitor";
import responseBudgetRouter from "./response-budget";
import readmeUpdaterRouter from "./readme-updater";
import runtimeSecurityRouter from "./runtime-security";
import aiDataModelRouter from "./ai-data-model";
import fileAnnotationsRouter from "./file-annotations";
import logShippingRouter from "./log-shipping";
import revenueAnalyticsRouter from "./revenue-analytics";
import errorPagesRouter from "./error-pages";
import coverageBadgeRouter from "./coverage-badge";
import gracefulShutdownRouter from "./graceful-shutdown";
import dbProvisioningRouter from "./db-provisioning";
import aiQueryOptimizerRouter from "./ai-query-optimizer";
import deployWebSocketRouter from "./deploy-websocket";
import startupOptimizerRouter from "./startup-optimizer";
import originFailoverRouter from "./origin-failover";
import ownershipReportRouter from "./ownership-report";
import runtimeUpdaterRouter from "./runtime-updater";
import requestQueueRouter from "./request-queue";
import formatCIRouter from "./format-ci";
import errorPatternsRouter from "./error-patterns";
import aiInfraRecommendRouter from "./ai-infra-recommend";
import secretInjectionRouter from "./secret-injection";
import deployRateLimitRouter from "./deploy-ratelimit";
import commitLinterRouter from "./commit-linter";
import cpuThrottleRouter from "./cpu-throttle";
import aiResponsiveRouter from "./ai-responsive";
import memoryProfilerRouter from "./memory-profiler";
import webhookRetryRouter from "./webhook-retry";
import styleMigrationRouter from "./style-migration";
import imageGCRouter from "./image-gc";
import aiCommitReviewRouter from "./ai-commit-review";
import errorAlertingRouter from "./error-alerting";
import bandwidthLimiterRouter from "./bandwidth-limiter";
import blueGreenRouter from "./blue-green";
import techDebtRouter from "./tech-debt";
import nginxConfigRouter from "./nginx-config";
import edgeDeployRouter from "./edge-deploy";
import diffChangelogRouter from "./diff-changelog";
import containerIPCRouter from "./container-ipc";
import aiComponentGenRouter from "./ai-component-gen";
import logFormatRouter from "./log-format";
import reviewAutomationRouter from "./review-automation";
import liveDebugRouter from "./live-debug";
import requestValidationRouter from "./request-validation";
import clientGenRouter from "./client-gen";
import fileSyncRouter from "./file-sync";
import aiReadmeRouter from "./ai-readme";
import mutationTestingRouter from "./mutation-testing";
import runtimeInspectRouter from "./runtime-inspect";
import autoRollbackRouter from "./auto-rollback";
import licenseComplianceRouter from "./license-compliance";
import snapshotExportRouter from "./snapshot-export";
import aiComponentLibRouter from "./ai-component-lib";
import requestDedupRouter from "./request-dedup";
import branchProtectionRouter from "./branch-protection";
import rateLimitDashboardRouter from "./rate-limit-dashboard";
import perfTestingRouter from "./perf-testing";
import depLicenseRouter from "./dep-license";
import trafficAnalyticsRouter from "./traffic-analytics";
import docWikiRouter from "./doc-wiki";
import importSuggestionsRouter from "./import-suggestions";
import envComparisonRouter from "./env-comparison";
import networkDashboardRouter from "./network-dashboard";
import badgeGeneratorRouter from "./badge-generator";
import securityPatchingRouter from "./security-patching";
import debugToolsRouter from "./debug-tools";
import changelogFeedRouter from "./changelog-feed";
import terminalAutocompleteRouter from "./terminal-autocomplete";
import monitoringAlertsRouter from "./monitoring-alerts";
import codeSearchRouter from "./code-search";
import templateVersioningRouter from "./template-versioning";
import layoutPresetsRouter from "./layout-presets";
import vulnScanRouter from "./vuln-scan";
import embedWidgetRouter from "./embed-widget";
import migrationToolRouter from "./migration-tool";
import statusIncidentsRouter from "./status-incidents";
import apiTestingRouter from "./api-testing";
import templateWizardRouter from "./template-wizard";
import errorDashboardRouter from "./error-dashboard";
import fsSnapshotDiffRouter from "./fs-snapshot-diff";
import extensionsApiRouter from "./extensions-api";
import canaryAnalysisRouter from "./canary-analysis";
import sitemapGenRouter from "./sitemap-gen";
import codeSnippetsRouter from "./code-snippets";
import previewCommentsRouter from "./preview-comments";
import logAnalysisRouter from "./log-analysis";
import milestoneTrackingRouter from "./milestone-tracking";
import issueTrackerRouter from "./issue-tracker";
import issuesRouter from "./issues";
import i18nRouter from "./i18n";
import keyboardShortcutsRouter from "./keyboard-shortcuts";
import fileDiffRouter from "./file-diff";
import projectSnapshotsRouter from "./project-snapshots";
import dbBrowserRouter from "./db-browser";
import collabTodosRouter from "./collab-todos";
import deployTestingRouter from "./deploy-testing";
import aiArchitectRouter from "./ai-architect";
import geoRoutingRouter from "./geo-routing";
import deploymentRegionRoutingRouter from "./deployment-region-routing";
import jobQueueRouter from "./job-queue";
import adminKpiRouter from "./admin-kpi";
import auditLogRouter from "./audit-log";
// Legacy two-factor routes removed — replaced by secure /security/2fa/* endpoints
import referralRouter from "./referral";
import statusPageRouter from "./status-page";
import changelogPageRouter from "./changelog-page";
import realtimeCollabRouter from "./realtime-collab";
import dbSchemaExpandRouter from "./db-schema-expand";
import containerEngineRouter from "./container-engine";
import githubIntegrationRouter from "./github-integration";
import aiFeaturesRouter from "./ai-features";
import deployPipelineRouter from "./deploy-pipeline";
import notificationSystemRouter from "./notification-system";
import exploreSocialRouter from "./explore-social";
import teamManagementRouter from "./team-management";
import billingSubscriptionsRouter from "./billing-subscriptions";
import projectAnalyticsRouter from "./project-analytics";
import accessControlRouter from "./access-control";
import workspaceSettingsRouter from "./workspace-settings";
import assetStorageRouter from "./asset-storage";
import projectSecretsRouter from "./project-secrets";
import previewDeploymentsRouter from "./preview-deployments";
import domainManagementRouter from "./domain-management";
import activityFeedRouter from "./activity-feed";
import usageLimitsRouter from "./usage-limits";
import webhookSystemRouter from "./webhook-system";
import userOnboardingRouter from "./user-onboarding";
import featureFlagsRouter from "./feature-flags";
import supportTicketsRouter from "./support-tickets";
import codeReviewSystemRouter from "./code-review-system";
import crashReportsRouter from "./crash-reports";
import cloudFunctionsRouter from "./cloud-functions";
import scheduledTasksRouter from "./scheduled-tasks";
import edgeConfigRouter from "./edge-config";
import databaseBackupsRouter from "./database-backups";
import logStreamingRouter from "./log-streaming";
import apiKeysRouter from "./api-keys";
import searchIndexRouter from "./search-index";
import emailServiceRouter from "./email-service";
import stripeBillingRouter from "./stripe-billing";
import ssoProviderRouter from "./sso-provider";
import ipFilteringRouter from "./ip-filtering";
import sessionManagerRouter from "./session-manager";
import gdprComplianceRouter from "./gdpr-compliance";
import deploymentStrategiesRouter from "./deployment-strategies";
import platformMetricsRouter from "./platform-metrics";
import graphqlApiRouter from "./graphql-api";
import cliToolsRouter from "./cli-tools";
import projectArchivalRouter from "./project-archival";
import objectStorageRouter from "./object-storage";
import serviceMeshRouter from "./service-mesh";
import learningPathsRouter from "./learning-paths";
import hackathonsRouter from "./hackathons";
import workspaceSyncRouter from "./workspace-sync";
import codeReviewAiRouter from "./code-review-ai";
import containerSnapshotsRouter from "./container-snapshots";
import liveShareRouter from "./live-share";
import projectImportRouter from "./project-import";
import projectExportRouter from "./project-export";
import containerLogsRouter from "./container-logs";
import userPreferencesRouter from "./user-preferences";
import buildCacheRouter from "./build-cache";
import customRunnersRouter from "./custom-runners";
import projectTemplatesStoreRouter from "./project-templates-store";
import debugSessionsRouter from "./debug-sessions";
import projectVariablesRouter from "./project-variables";
import resourceLimitsRouter from "./resource-limits";
import projectBadgesRouter from "./project-badges";
import deployRollbackRouter from "./deploy-rollback";
import projectForksRouter from "./project-forks";
import codeFormattingRouter from "./code-formatting";
import projectMilestonesRouter from "./project-milestones";
import userActivityLogRouter from "./user-activity-log";
import gpuRouter from "./gpu";
import domainsRouter from "./domains";
import billingRouter from "./billing";
import creditsRouter from "./credits";
import billingInvoicesRouter from "./billing-invoices";
import billingStripeRouter from "./billing-stripe";
import adminCreditsRouter from "./admin-credits";
import agentChatRouter from "./agent-chat";
import mobileRouter from "./mobile";
import buildhubRouter from "./buildhub";
import bountiesRouter from "./bounties";
import securityRouter from "./security";
import aiSmartRouterRouter from "./ai-smart-router";
import creditRolloverRouter from "./credit-rollover";
import scimRouter from "./scim";
import designTemplatesRouter from "./design-templates";
import aiBenchmarkRouter from "./ai-benchmark";
import differentiatorsRouter from "./differentiators";
import autoscaleRouter from "./autoscale";
import staticDeploymentsRouter from "./static-deployments";
import baasRouter from "./baas";
import mcpToolsRouter from "./mcp-tools";
import whiteLabelRouter from "./white-label";
import internalPublishRouter from "./internal-publish";
import designTokensRouter from "./design-tokens";
import sharingControlsRouter from "./sharing-controls";
import publishingControlsRouter from "./publishing-controls";
import knowledgeBaseRouter from "./knowledge-base";
import securityCenterRouter from "./security-center";
import orgPoliciesRouter from "./org-policies";
import { authLimiter, aiLimiter, uploadLimiter, deployLimiter, billingLimiter } from "../middlewares/rateLimit";
import { requireApiKeyScope } from "../middlewares/apiKeyScope";

const router: IRouter = Router();

router.use(securityRouter);
router.use(aiLimiter, aiSmartRouterRouter);
router.use(billingLimiter, creditRolloverRouter);
router.use(scimRouter);
router.use(designTemplatesRouter);
router.use(aiLimiter, aiBenchmarkRouter);
router.use(authLimiter, authRouter);
router.use(exportRouter);
router.use(formatRouter);
router.use(feedbackRouter);
router.use(healthRouter);
router.use(profileRouter);
router.use(requireApiKeyScope("read"), projectsRouter);
router.use(requireApiKeyScope("write"), filesRouter);
router.use(templatesRouter);
router.use(collaboratorsRouter);
router.use(deployLimiter, requireApiKeyScope("write"), deploymentsRouter);
router.use(exploreRouter);
router.use(dashboardRouter);
router.use(starsRouter);
router.use(notificationsRouter);
router.use(aiLimiter, aiRouter);
router.use(aiLimiter, aiMultiRouter);
router.use(aiLimiter, aiGatewayRouter);
router.use(aiLimiter, agentRouter);
router.use(commentsRouter);
router.use(requireApiKeyScope("admin"), adminRouter);
router.use(requireApiKeyScope("write"), settingsRouter);
router.use(integrationsRouter);
router.use(migrationsRouter);
router.use(githubRouter);
router.use(lintRouter);
router.use(gitRouter);
router.use(analyticsRouter);
router.use(databaseRouter);
router.use(snippetsRouter);
router.use(alwaysOnRouter);
router.use(containersRouter);
router.use(wsStatsRouter);
router.use(reviewsRouter);
router.use(liveSessionsRouter);
router.use(searchRouter);
router.use(oauthAppsRouter);
router.use(webhooksRouter);
router.use(environmentRouter);
router.use(requireApiKeyScope("write"), organizationsRouter);
router.use(portsRouter);
router.use(badgesRouter);
router.use(fileWatcherRouter);
router.use(transfersRouter);
router.use(sslRouter);
router.use(snapshotsRouter);
router.use(replRouter);
router.use(githubPrRouter);
router.use(containerNetworkRouter);
router.use(coverageRouter);
router.use(readmeRouter);
router.use(dbSyncRouter);
router.use(imageBuilderRouter);
router.use(perfTestRouter);
router.use(licenseCheckerRouter);
router.use(todosRouter);
router.use(trafficRouter);
router.use(execHistoryRouter);
router.use(wikiRouter);
router.use(timeTrackingRouter);
router.use(importAnalyzerRouter);
router.use(multiRegionRouter);
router.use(costOptimizerRouter);
router.use(deployAlertsRouter);
router.use(imageScanRouter);
router.use(socialCardsRouter);
router.use(incidentsRouter);
router.use(feedsRouter);
router.use(autoPatchRouter);
router.use(typeDocsRouter);
router.use(embedRouter);
router.use(projectMigrationRouter);
router.use(apiTesterRouter);
router.use(errorTrackingRouter);
router.use(fsDiffRouter);
router.use(starterKitsRouter);
router.use(onboardingAnalyticsRouter);
router.use(backupVerifyRouter);
router.use(prReviewRouter);
router.use(forecastingRouter);
router.use(warmPoolRouter);
router.use(trafficShapingRouter);
router.use(languageServerRouter);
router.use(complianceRouter);
router.use(multiTenantRouter);
router.use(rollingUpdateRouter);
router.use(autoMigrateRouter);
router.use(containerAlertsRouter);
router.use(deployChangelogRouter);
router.use(templateCiRouter);
router.use(funnelAnalyticsRouter);
router.use(aiLimiter, aiCommitRouter);
router.use(fileEncryptionRouter);
router.use(deploySecretRotationRouter);
router.use(fileLockingRouter);
router.use(containerDnsRouter);
router.use(aiLimiter, aiNamingRouter);
router.use(previewBotRouter);
router.use(starterGenRouter);
router.use(cdnCacheRouter);
router.use(aiLimiter, aiSqlRouter);
router.use(wafRouter);
router.use(execAuditRouter);
router.use(slaMonitorRouter);
router.use(costTagsRouter);
router.use(analyticsExportRouter);
router.use(imageOptimizerRouter);
router.use(templateAnalyticsRouter);
router.use(autoHealingRouter);
router.use(fileNotificationsRouter);
router.use(execTimeoutRouter);
router.use(aiLimiter, aiStyleRouter);
router.use(trafficMirrorRouter);
router.use(sslMonitorRouter);
router.use(duplicationDetectorRouter);
router.use(networkPolicyRouter);
router.use(aiLimiter, aiApiDesignRouter);
router.use(envPromotionRouter);
router.use(fsMonitorRouter);
router.use(responseBudgetRouter);
router.use(readmeUpdaterRouter);
router.use(runtimeSecurityRouter);
router.use(aiLimiter, aiDataModelRouter);
router.use(fileAnnotationsRouter);
router.use(logShippingRouter);
router.use(revenueAnalyticsRouter);
router.use(errorPagesRouter);
router.use(coverageBadgeRouter);
router.use(gracefulShutdownRouter);
router.use(dbProvisioningRouter);
router.use(aiLimiter, aiQueryOptimizerRouter);
router.use(deployWebSocketRouter);
router.use(startupOptimizerRouter);
router.use(originFailoverRouter);
router.use(ownershipReportRouter);
router.use(runtimeUpdaterRouter);
router.use(requestQueueRouter);
router.use(formatCIRouter);
router.use(errorPatternsRouter);
router.use(aiLimiter, aiInfraRecommendRouter);
router.use(secretInjectionRouter);
router.use(deployRateLimitRouter);
router.use(commitLinterRouter);
router.use(cpuThrottleRouter);
router.use(aiLimiter, aiResponsiveRouter);
router.use(memoryProfilerRouter);
router.use(webhookRetryRouter);
router.use(styleMigrationRouter);
router.use(imageGCRouter);
router.use(aiCommitReviewRouter);
router.use(errorAlertingRouter);
router.use(bandwidthLimiterRouter);
router.use(blueGreenRouter);
router.use(techDebtRouter);
router.use(nginxConfigRouter);
router.use(edgeDeployRouter);
router.use(diffChangelogRouter);
router.use(containerIPCRouter);
router.use(aiLimiter, aiComponentGenRouter);
router.use(logFormatRouter);
router.use(reviewAutomationRouter);
router.use(liveDebugRouter);
router.use(requestValidationRouter);
router.use(clientGenRouter);
router.use(fileSyncRouter);
router.use(aiLimiter, aiReadmeRouter);
router.use(mutationTestingRouter);
router.use(runtimeInspectRouter);
router.use(autoRollbackRouter);
router.use(licenseComplianceRouter);
router.use(snapshotExportRouter);
router.use(aiLimiter, aiComponentLibRouter);
router.use(requestDedupRouter);
router.use(branchProtectionRouter);
router.use(rateLimitDashboardRouter);
router.use(perfTestingRouter);
router.use(depLicenseRouter);
router.use(trafficAnalyticsRouter);
router.use(docWikiRouter);
router.use(importSuggestionsRouter);
router.use(envComparisonRouter);
router.use(networkDashboardRouter);
router.use(badgeGeneratorRouter);
router.use(securityPatchingRouter);
router.use(debugToolsRouter);
router.use(changelogFeedRouter);
router.use(terminalAutocompleteRouter);
router.use(monitoringAlertsRouter);
router.use(codeSearchRouter);
router.use(templateVersioningRouter);
router.use(layoutPresetsRouter);
router.use(vulnScanRouter);
router.use(embedWidgetRouter);
router.use(migrationToolRouter);
router.use(statusIncidentsRouter);
router.use(apiTestingRouter);
router.use(templateWizardRouter);
router.use(errorDashboardRouter);
router.use(fsSnapshotDiffRouter);
router.use(extensionsApiRouter);
router.use(canaryAnalysisRouter);
router.use(sitemapGenRouter);
router.use(codeSnippetsRouter);
router.use(previewCommentsRouter);
router.use(logAnalysisRouter);
router.use(milestoneTrackingRouter);
router.use(issueTrackerRouter);
router.use(issuesRouter);
router.use(i18nRouter);
router.use(keyboardShortcutsRouter);
router.use(fileDiffRouter);
router.use(projectSnapshotsRouter);
router.use(dbBrowserRouter);
router.use(collabTodosRouter);
router.use(deployTestingRouter);
router.use(aiLimiter, aiArchitectRouter);
router.use(geoRoutingRouter);
router.use(deploymentRegionRoutingRouter);
router.use(jobQueueRouter);
router.use(adminKpiRouter);
router.use(auditLogRouter);
// twoFactorRouter removed — use securityRouter for 2FA
router.use(referralRouter);
router.use(statusPageRouter);
router.use(changelogPageRouter);
router.use(realtimeCollabRouter);
router.use(dbSchemaExpandRouter);
router.use(containerEngineRouter);
router.use(githubIntegrationRouter);
router.use(aiLimiter, aiFeaturesRouter);
router.use(deployPipelineRouter);
router.use(notificationSystemRouter);
router.use(exploreSocialRouter);
router.use(teamManagementRouter);
router.use(billingLimiter, billingSubscriptionsRouter);
router.use(projectAnalyticsRouter);
router.use(accessControlRouter);
router.use(workspaceSettingsRouter);
router.use(uploadLimiter, assetStorageRouter);
router.use(projectSecretsRouter);
router.use(previewDeploymentsRouter);
router.use(domainManagementRouter);
router.use(activityFeedRouter);
router.use(usageLimitsRouter);
router.use(webhookSystemRouter);
router.use(userOnboardingRouter);
router.use(featureFlagsRouter);
router.use(supportTicketsRouter);
router.use(codeReviewSystemRouter);
router.use(crashReportsRouter);
router.use(cloudFunctionsRouter);
router.use(scheduledTasksRouter);
router.use(edgeConfigRouter);
router.use(databaseBackupsRouter);
router.use(logStreamingRouter);
router.use(apiKeysRouter);
router.use(searchIndexRouter);
router.use(emailServiceRouter);
router.use(billingLimiter, stripeBillingRouter);
router.use(requireApiKeyScope("admin"), ssoProviderRouter);
router.use(requireApiKeyScope("admin"), ipFilteringRouter);
router.use(requireApiKeyScope("write"), sessionManagerRouter);
router.use(gdprComplianceRouter);
router.use(deploymentStrategiesRouter);
router.use(platformMetricsRouter);
router.use(graphqlApiRouter);
router.use(cliToolsRouter);
router.use(projectArchivalRouter);
router.use(objectStorageRouter);
router.use(serviceMeshRouter);
router.use(learningPathsRouter);
router.use(hackathonsRouter);
router.use(workspaceSyncRouter);
router.use(aiLimiter, codeReviewAiRouter);
router.use(containerSnapshotsRouter);
router.use(liveShareRouter);
router.use(projectImportRouter);
router.use(projectExportRouter);
router.use(containerLogsRouter);
router.use(userPreferencesRouter);
router.use(buildCacheRouter);
router.use(customRunnersRouter);
router.use(projectTemplatesStoreRouter);
router.use(debugSessionsRouter);
router.use(projectVariablesRouter);
router.use(resourceLimitsRouter);
router.use(projectBadgesRouter);
router.use(deployRollbackRouter);
router.use(projectForksRouter);
router.use(codeFormattingRouter);
router.use(projectMilestonesRouter);
router.use(userActivityLogRouter);
router.use(gpuRouter);
router.use(domainsRouter);
router.use(billingLimiter, billingRouter);
router.use(billingLimiter, creditsRouter);
router.use(billingLimiter, billingInvoicesRouter);
router.use(billingLimiter, billingStripeRouter);
// stripeWebhookRouter is mounted in app.ts BEFORE express.json() so the
// signature verification can read the raw body. Do not mount it here.
router.use(adminCreditsRouter);
router.use(agentChatRouter);
router.use(mobileRouter);
router.use(buildhubRouter);
router.use(bountiesRouter);
router.use("/differentiators", differentiatorsRouter);
router.use(deployLimiter, autoscaleRouter);
router.use(deployLimiter, staticDeploymentsRouter);
router.use(baasRouter);
router.use(mcpToolsRouter);
router.use(whiteLabelRouter);
router.use(internalPublishRouter);
router.use(designTokensRouter);
router.use(sharingControlsRouter);
router.use(publishingControlsRouter);
router.use(knowledgeBaseRouter);
router.use(securityCenterRouter);
router.use(orgPoliciesRouter);

export default router;
