import { db, templatesTable } from "@workspace/db";

const templates = [
  {
    name: "Node Express API",
    slug: "node-express-api",
    description: "A production-ready Express.js REST API with routing, middleware, and error handling",
    language: "javascript",
    iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg",
    runCommand: "node server.js",
    entryFile: "server.js",
    dockerImage: "node:20-alpine",
    sortOrder: 1,
    filesSnapshot: {
      "server.js": [
        'const express = require("express");',
        'const cors = require("cors");',
        'const apiRoutes = require("./routes/api");',
        "",
        "const app = express();",
        "",
        "app.use(cors());",
        "app.use(express.json());",
        "app.use(express.urlencoded({ extended: true }));",
        "",
        'app.use("/api", apiRoutes);',
        "",
        "app.use((err, req, res, next) => {",
        '  console.error("Error:", err.message);',
        "  res.status(err.status || 500).json({",
        '    error: err.message || "Internal Server Error",',
        "  });",
        "});",
        "",
        "const PORT = process.env.PORT || 3000;",
        "app.listen(PORT, () => {",
        "  console.log(`Server running on port ${PORT}`);",
        "});",
      ].join("\n"),
      "routes/api.js": [
        'const express = require("express");',
        "const router = express.Router();",
        "",
        "let items = [",
        '  { id: 1, name: "Item One", status: "active" },',
        '  { id: 2, name: "Item Two", status: "active" },',
        "];",
        "",
        'router.get("/health", (req, res) => {',
        '  res.json({ status: "ok", uptime: process.uptime() });',
        "});",
        "",
        'router.get("/items", (req, res) => {',
        "  res.json({ items, total: items.length });",
        "});",
        "",
        'router.get("/items/:id", (req, res) => {',
        "  const item = items.find((i) => i.id === parseInt(req.params.id));",
        '  if (!item) return res.status(404).json({ error: "Not found" });',
        "  res.json(item);",
        "});",
        "",
        'router.post("/items", (req, res) => {',
        "  const item = { id: items.length + 1, ...req.body };",
        "  items.push(item);",
        "  res.status(201).json(item);",
        "});",
        "",
        'router.delete("/items/:id", (req, res) => {',
        "  items = items.filter((i) => i.id !== parseInt(req.params.id));",
        '  res.json({ message: "Deleted" });',
        "});",
        "",
        "module.exports = router;",
      ].join("\n"),
      "package.json": JSON.stringify({
        name: "express-api",
        version: "1.0.0",
        main: "server.js",
        scripts: { start: "node server.js", dev: "node --watch server.js" },
        dependencies: { express: "^4.21.0", cors: "^2.8.5" },
      }, null, 2),
      ".env": "PORT=3000\nNODE_ENV=development",
      "README.md": "# Express API\n\nA REST API built with Express.js.\n\n## Setup\n\n```bash\nnpm install\nnpm run dev\n```\n\n## Endpoints\n\n- `GET /api/health` — Health check\n- `GET /api/items` — List items\n- `POST /api/items` — Create item\n- `DELETE /api/items/:id` — Delete item\n",
    },
  },
  {
    name: "React + Vite",
    slug: "react-vite",
    description: "A modern React app with Vite, TypeScript, and CSS Modules",
    language: "typescript",
    iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
    runCommand: "npm run dev",
    entryFile: "src/App.tsx",
    dockerImage: "node:20-alpine",
    sortOrder: 2,
    filesSnapshot: {
      "src/App.tsx": [
        'import { useState } from "react";',
        'import "./App.css";',
        "",
        "export default function App() {",
        "  const [count, setCount] = useState(0);",
        "",
        "  return (",
        '    <div className="app">',
        '      <header className="header">',
        "        <h1>CodeCloud React App</h1>",
        "        <p>Edit src/App.tsx and save to reload.</p>",
        "      </header>",
        '      <main className="main">',
        '        <button className="counter-btn" onClick={() => setCount((c) => c + 1)}>',
        "          Count: {count}",
        "        </button>",
        "      </main>",
        "    </div>",
        "  );",
        "}",
      ].join("\n"),
      "src/main.tsx": 'import { StrictMode } from "react";\nimport { createRoot } from "react-dom/client";\nimport App from "./App";\nimport "./index.css";\n\ncreateRoot(document.getElementById("root")!).render(\n  <StrictMode>\n    <App />\n  </StrictMode>\n);',
      "src/App.css": ".app {\n  text-align: center;\n  padding: 2rem;\n}\n\n.header h1 {\n  font-size: 2rem;\n  margin-bottom: 0.5rem;\n}\n\n.counter-btn {\n  padding: 0.75rem 1.5rem;\n  font-size: 1.1rem;\n  border-radius: 8px;\n  border: 1px solid #646cff;\n  background: transparent;\n  color: #646cff;\n  cursor: pointer;\n  transition: all 0.2s;\n}\n\n.counter-btn:hover {\n  background: #646cff;\n  color: white;\n}",
      "src/index.css": ":root {\n  font-family: system-ui, sans-serif;\n  color: #ffffffde;\n  background: #242424;\n}\n\nbody {\n  margin: 0;\n  min-height: 100vh;\n}",
      "index.html": '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>React App</title>\n</head>\n<body>\n  <div id="root"></div>\n  <script type="module" src="/src/main.tsx"></script>\n</body>\n</html>',
      "vite.config.ts": 'import { defineConfig } from "vite";\nimport react from "@vitejs/plugin-react";\n\nexport default defineConfig({\n  plugins: [react()],\n});',
      "tsconfig.json": '{\n  "compilerOptions": {\n    "target": "ES2020",\n    "module": "ESNext",\n    "moduleResolution": "bundler",\n    "jsx": "react-jsx",\n    "strict": true,\n    "skipLibCheck": true\n  },\n  "include": ["src"]\n}',
      "package.json": JSON.stringify({
        name: "react-vite-app",
        scripts: { dev: "vite", build: "tsc && vite build", preview: "vite preview" },
        dependencies: { react: "^19", "react-dom": "^19" },
        devDependencies: { vite: "^6", "@vitejs/plugin-react": "^4", typescript: "^5" },
      }, null, 2),
    },
  },
  {
    name: "Next.js",
    slug: "nextjs",
    description: "A Next.js 14 app with App Router, TypeScript, and Tailwind CSS",
    language: "typescript",
    iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
    runCommand: "npm run dev",
    entryFile: "app/page.tsx",
    dockerImage: "node:20-alpine",
    sortOrder: 3,
    filesSnapshot: {
      "app/layout.tsx": [
        'import type { Metadata } from "next";',
        'import "./globals.css";',
        "",
        "export const metadata: Metadata = {",
        '  title: "My App",',
        '  description: "Built on CodeCloud",',
        "};",
        "",
        "export default function RootLayout({ children }: { children: React.ReactNode }) {",
        "  return (",
        '    <html lang="en">',
        '      <body className="antialiased">{children}</body>',
        "    </html>",
        "  );",
        "}",
      ].join("\n"),
      "app/page.tsx": [
        "export default function Home() {",
        "  return (",
        '    <main className="flex min-h-screen flex-col items-center justify-center p-8">',
        '      <h1 className="text-4xl font-bold mb-4">Welcome to CodeCloud</h1>',
        '      <p className="text-lg text-gray-400">Edit app/page.tsx to get started.</p>',
        '      <div className="mt-8 grid grid-cols-2 gap-4">',
        '        <a href="/about" className="p-4 border rounded-lg hover:bg-gray-800 transition">',
        '          <h2 className="font-semibold">About &rarr;</h2>',
        '          <p className="text-sm text-gray-500">Learn more about the project</p>',
        "        </a>",
        '        <a href="/api/hello" className="p-4 border rounded-lg hover:bg-gray-800 transition">',
        '          <h2 className="font-semibold">API &rarr;</h2>',
        '          <p className="text-sm text-gray-500">Check the API route</p>',
        "        </a>",
        "      </div>",
        "    </main>",
        "  );",
        "}",
      ].join("\n"),
      "app/about/page.tsx": 'export default function About() {\n  return (\n    <main className="p-8 max-w-2xl mx-auto">\n      <h1 className="text-3xl font-bold mb-4">About</h1>\n      <p>This is a Next.js app running on CodeCloud.</p>\n    </main>\n  );\n}',
      "app/api/hello/route.ts": 'import { NextResponse } from "next/server";\n\nexport async function GET() {\n  return NextResponse.json({ message: "Hello from the API!" });\n}',
      "app/globals.css": "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\nbody {\n  background: #0a0a0a;\n  color: #ededed;\n}",
      "next.config.js": "/** @type {import('next').NextConfig} */\nconst nextConfig = {};\nmodule.exports = nextConfig;",
      "tailwind.config.js": '/** @type {import("tailwindcss").Config} */\nmodule.exports = {\n  content: ["./app/**/*.{js,ts,jsx,tsx}"],\n  theme: { extend: {} },\n  plugins: [],\n};',
      "package.json": JSON.stringify({
        name: "nextjs-app",
        scripts: { dev: "next dev", build: "next build", start: "next start" },
        dependencies: { next: "^14", react: "^19", "react-dom": "^19" },
        devDependencies: { tailwindcss: "^3", autoprefixer: "^10", postcss: "^8" },
      }, null, 2),
    },
  },
  {
    name: "Python Flask",
    slug: "flask",
    description: "A Flask web app with templates, static files, and API routes",
    language: "python",
    iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original.svg",
    runCommand: "python app.py",
    entryFile: "app.py",
    dockerImage: "python:3.12-slim",
    sortOrder: 4,
    filesSnapshot: {
      "app.py": [
        "from flask import Flask, jsonify, render_template, request",
        "",
        "app = Flask(__name__)",
        "",
        "items = []",
        "",
        '@app.route("/")',
        "def home():",
        '    return render_template("index.html", title="CodeCloud Flask App")',
        "",
        '@app.route("/api/health")',
        "def health():",
        '    return jsonify({"status": "ok"})',
        "",
        '@app.route("/api/items", methods=["GET"])',
        "def list_items():",
        '    return jsonify({"items": items})',
        "",
        '@app.route("/api/items", methods=["POST"])',
        "def create_item():",
        "    data = request.get_json()",
        '    item = {"id": len(items) + 1, "name": data.get("name", "Untitled")}',
        "    items.append(item)",
        "    return jsonify(item), 201",
        "",
        'if __name__ == "__main__":',
        '    app.run(host="0.0.0.0", port=3000, debug=True)',
      ].join("\n"),
      "templates/index.html": '<!DOCTYPE html>\n<html>\n<head><title>{{ title }}</title></head>\n<body>\n  <h1>{{ title }}</h1>\n  <p>Welcome to your Flask application!</p>\n</body>\n</html>',
      "static/style.css": "body {\n  font-family: system-ui, sans-serif;\n  max-width: 800px;\n  margin: 0 auto;\n  padding: 2rem;\n}",
      "requirements.txt": "flask>=3.0.0\ngunicorn>=21.2.0",
      "README.md": "# Flask App\n\n## Setup\n\n```bash\npip install -r requirements.txt\npython app.py\n```\n",
    },
  },
  {
    name: "FastAPI",
    slug: "fastapi",
    description: "A FastAPI server with Pydantic models, CRUD routes, and auto-generated docs",
    language: "python",
    iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/fastapi/fastapi-original.svg",
    runCommand: "uvicorn main:app --host 0.0.0.0 --port 3000 --reload",
    entryFile: "main.py",
    dockerImage: "python:3.12-slim",
    sortOrder: 5,
    filesSnapshot: {
      "main.py": [
        "from fastapi import FastAPI, HTTPException",
        "from pydantic import BaseModel",
        "from typing import Optional",
        "from datetime import datetime",
        "",
        "app = FastAPI(title=\"CodeCloud API\", version=\"1.0.0\")",
        "",
        "class ItemCreate(BaseModel):",
        "    name: str",
        "    description: Optional[str] = None",
        "    price: float",
        "",
        "class Item(ItemCreate):",
        "    id: int",
        "    created_at: datetime",
        "",
        "items_db: list[Item] = []",
        "",
        '@app.get("/")',
        "async def root():",
        '    return {"message": "Welcome to CodeCloud FastAPI", "docs": "/docs"}',
        "",
        '@app.get("/api/health")',
        "async def health():",
        '    return {"status": "ok"}',
        "",
        '@app.get("/api/items", response_model=list[Item])',
        "async def list_items():",
        "    return items_db",
        "",
        '@app.post("/api/items", response_model=Item, status_code=201)',
        "async def create_item(item: ItemCreate):",
        "    new_item = Item(",
        "        id=len(items_db) + 1,",
        "        created_at=datetime.now(),",
        "        **item.model_dump(),",
        "    )",
        "    items_db.append(new_item)",
        "    return new_item",
        "",
        '@app.get("/api/items/{item_id}", response_model=Item)',
        "async def get_item(item_id: int):",
        "    item = next((i for i in items_db if i.id == item_id), None)",
        "    if not item:",
        '        raise HTTPException(status_code=404, detail="Item not found")',
        "    return item",
        "",
        '@app.delete("/api/items/{item_id}")',
        "async def delete_item(item_id: int):",
        "    global items_db",
        "    items_db = [i for i in items_db if i.id != item_id]",
        '    return {"message": "Deleted"}',
      ].join("\n"),
      "requirements.txt": "fastapi>=0.115.0\nuvicorn[standard]>=0.30.0\npydantic>=2.0.0",
      "README.md": "# FastAPI App\n\n## Setup\n\n```bash\npip install -r requirements.txt\nuvicorn main:app --reload\n```\n\nVisit `/docs` for interactive API documentation.\n",
    },
  },
  {
    name: "Go Gin",
    slug: "go-gin",
    description: "A Go web server with Gin framework, REST routes, and middleware",
    language: "go",
    iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg",
    runCommand: "go run main.go",
    entryFile: "main.go",
    dockerImage: "golang:1.22-alpine",
    sortOrder: 6,
    filesSnapshot: {
      "main.go": [
        "package main",
        "",
        "import (",
        '\t"net/http"',
        '\t"strconv"',
        "",
        '\t"github.com/gin-gonic/gin"',
        ")",
        "",
        "type Item struct {",
        '\tID   int    `json:"id"`',
        '\tName string `json:"name"`',
        '}',
        "",
        "var items = []Item{",
        '\t{ID: 1, Name: "First Item"},',
        '\t{ID: 2, Name: "Second Item"},',
        "}",
        "",
        "func main() {",
        "\tr := gin.Default()",
        "",
        '\tr.GET("/", func(c *gin.Context) {',
        "\t\tc.JSON(http.StatusOK, gin.H{",
        '\t\t\t"message": "Hello from CodeCloud!",',
        "\t\t})",
        "\t})",
        "",
        '\tr.GET("/api/health", func(c *gin.Context) {',
        '\t\tc.JSON(http.StatusOK, gin.H{"status": "ok"})',
        "\t})",
        "",
        '\tr.GET("/api/items", func(c *gin.Context) {',
        "\t\tc.JSON(http.StatusOK, items)",
        "\t})",
        "",
        '\tr.POST("/api/items", func(c *gin.Context) {',
        "\t\tvar item Item",
        "\t\tif err := c.ShouldBindJSON(&item); err != nil {",
        "\t\t\tc.JSON(http.StatusBadRequest, gin.H{\"error\": err.Error()})",
        "\t\t\treturn",
        "\t\t}",
        "\t\titem.ID = len(items) + 1",
        "\t\titems = append(items, item)",
        "\t\tc.JSON(http.StatusCreated, item)",
        "\t})",
        "",
        '\tr.Run(":3000")',
        "}",
      ].join("\n"),
      "go.mod": "module codecloud-app\n\ngo 1.22\n\nrequire github.com/gin-gonic/gin v1.9.1",
      "README.md": "# Go Gin API\n\n## Setup\n\n```bash\ngo mod tidy\ngo run main.go\n```\n",
    },
  },
  {
    name: "Rust Actix",
    slug: "rust-actix",
    description: "A Rust web server with Actix Web, JSON serialization, and error handling",
    language: "rust",
    iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rust/rust-original.svg",
    runCommand: "cargo run",
    entryFile: "src/main.rs",
    dockerImage: "rust:1.77-slim",
    sortOrder: 7,
    filesSnapshot: {
      "src/main.rs": [
        "use actix_web::{web, App, HttpServer, HttpResponse, middleware};",
        "use serde::{Deserialize, Serialize};",
        "use std::sync::Mutex;",
        "",
        "#[derive(Serialize, Deserialize, Clone)]",
        "struct Item {",
        "    id: u32,",
        "    name: String,",
        "}",
        "",
        "struct AppState {",
        "    items: Mutex<Vec<Item>>,",
        "}",
        "",
        "async fn health() -> HttpResponse {",
        '    HttpResponse::Ok().json(serde_json::json!({"status": "ok"}))',
        "}",
        "",
        "async fn list_items(data: web::Data<AppState>) -> HttpResponse {",
        '    let items = data.items.lock().unwrap();',
        "    HttpResponse::Ok().json(&*items)",
        "}",
        "",
        "async fn create_item(data: web::Data<AppState>, item: web::Json<Item>) -> HttpResponse {",
        '    let mut items = data.items.lock().unwrap();',
        "    let mut new_item = item.into_inner();",
        "    new_item.id = items.len() as u32 + 1;",
        "    items.push(new_item.clone());",
        "    HttpResponse::Created().json(new_item)",
        "}",
        "",
        "#[actix_web::main]",
        "async fn main() -> std::io::Result<()> {",
        '    println!("Server running at http://localhost:3000");',
        "    let data = web::Data::new(AppState {",
        "        items: Mutex::new(vec![",
        '            Item { id: 1, name: "First Item".to_string() },',
        "        ]),",
        "    });",
        "",
        "    HttpServer::new(move || {",
        "        App::new()",
        "            .app_data(data.clone())",
        "            .wrap(middleware::Logger::default())",
        '            .route("/api/health", web::get().to(health))',
        '            .route("/api/items", web::get().to(list_items))',
        '            .route("/api/items", web::post().to(create_item))',
        "    })",
        '    .bind("0.0.0.0:3000")?',
        "    .run()",
        "    .await",
        "}",
      ].join("\n"),
      "Cargo.toml": [
        "[package]",
        'name = "codecloud-app"',
        'version = "0.1.0"',
        'edition = "2021"',
        "",
        "[dependencies]",
        'actix-web = "4"',
        'serde = { version = "1", features = ["derive"] }',
        'serde_json = "1"',
        'tokio = { version = "1", features = ["full"] }',
      ].join("\n"),
      "README.md": "# Rust Actix Web\n\n## Setup\n\n```bash\ncargo run\n```\n",
    },
  },
  {
    name: "Ruby on Rails",
    slug: "ruby-rails",
    description: "A Ruby on Rails API-only app with model, controller, and routes",
    language: "ruby",
    iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rails/rails-original-wordmark.svg",
    runCommand: "rails server -p 3000",
    entryFile: "config/routes.rb",
    dockerImage: "ruby:3.3-slim",
    sortOrder: 8,
    filesSnapshot: {
      "Gemfile": 'source "https://rubygems.org"\n\ngem "rails", "~> 7.1"\ngem "puma", ">= 5.0"\ngem "sqlite3"\ngem "bootsnap", require: false',
      "config/routes.rb": [
        "Rails.application.routes.draw do",
        '  get "/api/health", to: "health#show"',
        "",
        "  namespace :api do",
        "    resources :items, only: [:index, :show, :create, :destroy]",
        "  end",
        "",
        '  root "health#show"',
        "end",
      ].join("\n"),
      "app/controllers/health_controller.rb": 'class HealthController < ApplicationController\n  def show\n    render json: { status: "ok", rails: Rails.version }\n  end\nend',
      "app/controllers/api/items_controller.rb": [
        "class Api::ItemsController < ApplicationController",
        "  def index",
        "    render json: Item.all",
        "  end",
        "",
        "  def show",
        "    render json: Item.find(params[:id])",
        "  end",
        "",
        "  def create",
        "    item = Item.new(item_params)",
        "    if item.save",
        "      render json: item, status: :created",
        "    else",
        "      render json: { errors: item.errors }, status: :unprocessable_entity",
        "    end",
        "  end",
        "",
        "  def destroy",
        "    Item.find(params[:id]).destroy",
        "    head :no_content",
        "  end",
        "",
        "  private",
        "",
        "  def item_params",
        "    params.require(:item).permit(:name, :description)",
        "  end",
        "end",
      ].join("\n"),
      "app/models/item.rb": "class Item < ApplicationRecord\n  validates :name, presence: true\nend",
      "README.md": "# Rails API\n\n## Setup\n\n```bash\nbundle install\nrails db:migrate\nrails server\n```\n",
    },
  },
  {
    name: "PHP Laravel",
    slug: "php-laravel",
    description: "A Laravel app with Eloquent models, API routes, and Blade views",
    language: "php",
    iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/laravel/laravel-original.svg",
    runCommand: "php artisan serve --port=3000",
    entryFile: "routes/web.php",
    dockerImage: "php:8.3-cli",
    sortOrder: 9,
    filesSnapshot: {
      "routes/web.php": [
        "<?php",
        "",
        "use Illuminate\\Support\\Facades\\Route;",
        "",
        "Route::get('/', function () {",
        "    return view('welcome');",
        "});",
      ].join("\n"),
      "routes/api.php": [
        "<?php",
        "",
        "use Illuminate\\Support\\Facades\\Route;",
        "use App\\Http\\Controllers\\ItemController;",
        "",
        "Route::get('/health', function () {",
        "    return response()->json(['status' => 'ok']);",
        "});",
        "",
        "Route::apiResource('items', ItemController::class);",
      ].join("\n"),
      "app/Http/Controllers/ItemController.php": [
        "<?php",
        "",
        "namespace App\\Http\\Controllers;",
        "",
        "use App\\Models\\Item;",
        "use Illuminate\\Http\\Request;",
        "",
        "class ItemController extends Controller",
        "{",
        "    public function index()",
        "    {",
        "        return Item::all();",
        "    }",
        "",
        "    public function store(Request $request)",
        "    {",
        "        $validated = $request->validate([",
        "            'name' => 'required|string|max:255',",
        "        ]);",
        "        return Item::create($validated);",
        "    }",
        "",
        "    public function show(Item $item)",
        "    {",
        "        return $item;",
        "    }",
        "",
        "    public function destroy(Item $item)",
        "    {",
        "        $item->delete();",
        "        return response()->noContent();",
        "    }",
        "}",
      ].join("\n"),
      "app/Models/Item.php": "<?php\n\nnamespace App\\Models;\n\nuse Illuminate\\Database\\Eloquent\\Model;\n\nclass Item extends Model\n{\n    protected $fillable = ['name', 'description'];\n}",
      "resources/views/welcome.blade.php": "<!DOCTYPE html>\n<html>\n<head><title>CodeCloud Laravel</title></head>\n<body>\n  <h1>Welcome to CodeCloud</h1>\n  <p>Edit routes/web.php to get started.</p>\n</body>\n</html>",
      "README.md": "# Laravel App\n\n## Setup\n\n```bash\ncomposer install\nphp artisan migrate\nphp artisan serve\n```\n",
    },
  },
  {
    name: "Static HTML",
    slug: "static-html",
    description: "A responsive static website with HTML, CSS, and vanilla JavaScript",
    language: "html",
    iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
    runCommand: "npx serve .",
    entryFile: "index.html",
    dockerImage: "node:20-alpine",
    sortOrder: 10,
    filesSnapshot: {
      "index.html": [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '  <meta charset="UTF-8" />',
        '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
        "  <title>My Website</title>",
        '  <link rel="stylesheet" href="css/style.css" />',
        "</head>",
        "<body>",
        "  <header>",
        '    <nav class="navbar">',
        '      <a href="/" class="logo">CodeCloud</a>',
        '      <ul class="nav-links">',
        '        <li><a href="#features">Features</a></li>',
        '        <li><a href="#about">About</a></li>',
        '        <li><a href="#contact">Contact</a></li>',
        "      </ul>",
        "    </nav>",
        "  </header>",
        '  <main class="hero">',
        "    <h1>Welcome to My Website</h1>",
        "    <p>A beautiful static site built on CodeCloud.</p>",
        '    <button id="cta-btn">Get Started</button>',
        "  </main>",
        '  <section id="features" class="section">',
        "    <h2>Features</h2>",
        '    <div class="grid">',
        '      <div class="card"><h3>Fast</h3><p>Lightning-fast load times</p></div>',
        '      <div class="card"><h3>Modern</h3><p>Clean, modern design</p></div>',
        '      <div class="card"><h3>Responsive</h3><p>Works on all devices</p></div>',
        "    </div>",
        "  </section>",
        '  <script src="js/main.js"></script>',
        "</body>",
        "</html>",
      ].join("\n"),
      "css/style.css": [
        "* { margin: 0; padding: 0; box-sizing: border-box; }",
        "body { font-family: system-ui, sans-serif; background: #0d1117; color: #c9d1d9; }",
        ".navbar { display: flex; justify-content: space-between; align-items: center; padding: 1rem 2rem; background: #161b22; }",
        ".logo { font-size: 1.5rem; font-weight: 700; color: #58a6ff; text-decoration: none; }",
        ".nav-links { display: flex; list-style: none; gap: 1.5rem; }",
        ".nav-links a { color: #8b949e; text-decoration: none; transition: color 0.2s; }",
        ".nav-links a:hover { color: #f0f6fc; }",
        ".hero { text-align: center; padding: 6rem 2rem; }",
        ".hero h1 { font-size: 3rem; margin-bottom: 1rem; }",
        ".hero p { font-size: 1.2rem; color: #8b949e; margin-bottom: 2rem; }",
        "#cta-btn { padding: 0.75rem 2rem; font-size: 1rem; border: none; border-radius: 6px; background: #238636; color: white; cursor: pointer; transition: background 0.2s; }",
        "#cta-btn:hover { background: #2ea043; }",
        ".section { padding: 4rem 2rem; max-width: 1000px; margin: 0 auto; }",
        ".section h2 { font-size: 2rem; margin-bottom: 2rem; text-align: center; }",
        ".grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1.5rem; }",
        ".card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.5rem; }",
        ".card h3 { margin-bottom: 0.5rem; color: #58a6ff; }",
      ].join("\n"),
      "js/main.js": 'document.getElementById("cta-btn").addEventListener("click", () => {\n  alert("Welcome to CodeCloud!");\n});\n\nconsole.log("Site loaded");',
      "README.md": "# Static Website\n\nA responsive static site.\n\n## Usage\n\nOpen `index.html` in a browser.\n",
    },
  },
  {
    name: "TypeScript CLI",
    slug: "typescript-cli",
    description: "A TypeScript command-line tool with argument parsing, colored output, and file I/O",
    language: "typescript",
    iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
    runCommand: "npx tsx src/index.ts",
    entryFile: "src/index.ts",
    dockerImage: "node:20-alpine",
    sortOrder: 11,
    filesSnapshot: {
      "src/index.ts": [
        'import { parseArgs } from "node:util";',
        'import { readFileSync, writeFileSync, existsSync } from "node:fs";',
        "",
        "const colors = {",
        '  reset: "\\x1b[0m",',
        '  green: "\\x1b[32m",',
        '  yellow: "\\x1b[33m",',
        '  red: "\\x1b[31m",',
        '  cyan: "\\x1b[36m",',
        '  bold: "\\x1b[1m",',
        "};",
        "",
        "function log(msg: string, color = colors.reset) {",
        "  console.log(`${color}${msg}${colors.reset}`);",
        "}",
        "",
        "interface Config {",
        "  name: string;",
        "  version: string;",
        "}",
        "",
        "function showHelp() {",
        '  log("\\nCodeCloud CLI Tool", colors.bold);',
        '  log("==================", colors.cyan);',
        '  log("\\nUsage: npx tsx src/index.ts [command] [options]");',
        '  log("\\nCommands:");',
        '  log("  init          Initialize a new project");',
        '  log("  info          Show project information");',
        '  log("  greet <name>  Greet someone");',
        '  log("  help          Show this help message");',
        "}",
        "",
        "function init() {",
        '  const config: Config = { name: "my-project", version: "1.0.0" };',
        '  writeFileSync("project.json", JSON.stringify(config, null, 2));',
        '  log("Project initialized!", colors.green);',
        "}",
        "",
        "function info() {",
        '  if (!existsSync("project.json")) {',
        '    log("No project.json found. Run init first.", colors.red);',
        "    return;",
        "  }",
        '  const config: Config = JSON.parse(readFileSync("project.json", "utf-8"));',
        "  log(`Project: ${config.name} v${config.version}`, colors.cyan);",
        "}",
        "",
        "const args = process.argv.slice(2);",
        'const command = args[0] || "help";',
        "",
        "switch (command) {",
        '  case "init": init(); break;',
        '  case "info": info(); break;',
        '  case "greet":',
        '    const name = args[1] || "World";',
        "    log(`Hello, ${name}!`, colors.green);",
        "    break;",
        "  default: showHelp();",
        "}",
      ].join("\n"),
      "tsconfig.json": JSON.stringify({
        compilerOptions: {
          target: "ES2022",
          module: "ESNext",
          moduleResolution: "bundler",
          strict: true,
          outDir: "dist",
          rootDir: "src",
          skipLibCheck: true,
        },
        include: ["src"],
      }, null, 2),
      "package.json": JSON.stringify({
        name: "typescript-cli",
        version: "1.0.0",
        type: "module",
        scripts: { start: "tsx src/index.ts", build: "tsc", dev: "tsx watch src/index.ts" },
        devDependencies: { typescript: "^5", tsx: "^4" },
      }, null, 2),
      "README.md": "# TypeScript CLI\n\nA command-line tool built with TypeScript.\n\n## Usage\n\n```bash\nnpx tsx src/index.ts help\nnpx tsx src/index.ts init\nnpx tsx src/index.ts greet Alice\n```\n",
    },
  },
  {
    name: "Java Spring Boot",
    slug: "java-spring-boot",
    description: "A Spring Boot REST API with controllers, services, and JPA entities",
    language: "java",
    iconUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg",
    runCommand: "./mvnw spring-boot:run",
    entryFile: "src/main/java/com/example/app/Application.java",
    dockerImage: "eclipse-temurin:21-jdk-alpine",
    sortOrder: 12,
    filesSnapshot: {
      "src/main/java/com/example/app/Application.java": [
        "package com.example.app;",
        "",
        "import org.springframework.boot.SpringApplication;",
        "import org.springframework.boot.autoconfigure.SpringBootApplication;",
        "",
        "@SpringBootApplication",
        "public class Application {",
        "    public static void main(String[] args) {",
        "        SpringApplication.run(Application.class, args);",
        "    }",
        "}",
      ].join("\n"),
      "src/main/java/com/example/app/controller/ItemController.java": [
        "package com.example.app.controller;",
        "",
        "import com.example.app.model.Item;",
        "import org.springframework.http.HttpStatus;",
        "import org.springframework.web.bind.annotation.*;",
        "",
        "import java.util.*;",
        "import java.util.concurrent.atomic.AtomicLong;",
        "",
        "@RestController",
        '@RequestMapping("/api")',
        "public class ItemController {",
        "    private final List<Item> items = new ArrayList<>();",
        "    private final AtomicLong counter = new AtomicLong(1);",
        "",
        '    @GetMapping("/health")',
        "    public Map<String, String> health() {",
        '        return Map.of("status", "ok");',
        "    }",
        "",
        '    @GetMapping("/items")',
        "    public List<Item> listItems() {",
        "        return items;",
        "    }",
        "",
        '    @PostMapping("/items")',
        "    @ResponseStatus(HttpStatus.CREATED)",
        "    public Item createItem(@RequestBody Item item) {",
        "        item.setId(counter.getAndIncrement());",
        "        items.add(item);",
        "        return item;",
        "    }",
        "}",
      ].join("\n"),
      "src/main/java/com/example/app/model/Item.java": [
        "package com.example.app.model;",
        "",
        "public class Item {",
        "    private Long id;",
        "    private String name;",
        "    private String description;",
        "",
        "    public Long getId() { return id; }",
        "    public void setId(Long id) { this.id = id; }",
        "    public String getName() { return name; }",
        "    public void setName(String name) { this.name = name; }",
        "    public String getDescription() { return description; }",
        "    public void setDescription(String description) { this.description = description; }",
        "}",
      ].join("\n"),
      "src/main/resources/application.properties": "server.port=3000\nspring.application.name=codecloud-app",
      "pom.xml": [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<project xmlns="http://maven.apache.org/POM/4.0.0"',
        '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
        '    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">',
        "    <modelVersion>4.0.0</modelVersion>",
        "    <parent>",
        "        <groupId>org.springframework.boot</groupId>",
        "        <artifactId>spring-boot-starter-parent</artifactId>",
        "        <version>3.2.0</version>",
        "    </parent>",
        "    <groupId>com.example</groupId>",
        "    <artifactId>codecloud-app</artifactId>",
        "    <version>1.0.0</version>",
        "    <dependencies>",
        "        <dependency>",
        "            <groupId>org.springframework.boot</groupId>",
        "            <artifactId>spring-boot-starter-web</artifactId>",
        "        </dependency>",
        "    </dependencies>",
        "    <build>",
        "        <plugins>",
        "            <plugin>",
        "                <groupId>org.springframework.boot</groupId>",
        "                <artifactId>spring-boot-maven-plugin</artifactId>",
        "            </plugin>",
        "        </plugins>",
        "    </build>",
        "</project>",
      ].join("\n"),
      "README.md": "# Spring Boot API\n\n## Setup\n\n```bash\n./mvnw spring-boot:run\n```\n\nAPI available at http://localhost:3000\n",
    },
  },
];

async function seed() {
  console.log("Seeding templates...");
  for (const template of templates) {
    await db.insert(templatesTable)
      .values(template)
      .onConflictDoNothing();
  }
  console.log(`Seeded ${templates.length} templates.`);
}

seed().then(() => process.exit(0)).catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
